name: Build Go

on:
  push:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.23'

    - name: Build frontend
      run: npm install && npm run build
      working-directory: web

    - name: Build
      run: go build

    - name: Upload build
      uses: actions/upload-artifact@v4
      with:
        name: localapps
        path: localapps
